"""Architecture guardrails for generated-content footer wording."""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

import pytest

pytestmark = pytest.mark.component


def test_generated_footer_has_single_owner() -> None:
    """All compilation renderers must use the canonical footer builder."""
    root = Path(__file__).parents[2]
    owner = (root / "src/apm_cli/compilation/footer.py").read_text(encoding="utf-8")
    guard = (root / "scripts/lint-architecture-boundaries.sh").read_text(encoding="utf-8")
    architecture = (root / ".github/instructions/architecture.instructions.md").read_text(
        encoding="utf-8"
    )

    assert owner.count("def build_generation_footer(") == 1
    assert "check_agents_footer_authority.py" in guard
    assert "| Generated-content footer ownership wording |" in architecture


def test_generated_footer_guard_rejects_parallel_wording(tmp_path: Path) -> None:
    """The boundary guard must reject footer wording duplicated by a renderer."""
    root = Path(__file__).parents[2]
    sandbox = tmp_path / "repo"
    paths = (
        "scripts/check_agents_footer_authority.py",
        "src/apm_cli/compilation/agents_compiler.py",
        "src/apm_cli/compilation/claude_formatter.py",
        "src/apm_cli/compilation/distributed_compiler.py",
        "src/apm_cli/compilation/footer.py",
        "src/apm_cli/compilation/template_builder.py",
    )
    for relative_path in paths:
        source = root / relative_path
        destination = sandbox / relative_path
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)

    consumer = sandbox / "src/apm_cli/compilation/template_builder.py"
    consumer.write_text(
        consumer.read_text(encoding="utf-8")
        + '\n_DUPLICATE_FOOTER = "This file was generated by APM CLI. '
        + 'Do not edit manually."\n',
        encoding="utf-8",
    )

    result = subprocess.run(
        (sys.executable, "scripts/check_agents_footer_authority.py", str(sandbox)),
        cwd=sandbox,
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 1
    assert "Generated footer wording must route through compilation/footer.py" in result.stdout


def test_generated_footer_guard_requires_executable_consumer_call(tmp_path: Path) -> None:
    """A comment mentioning the owner must not satisfy the boundary guard."""
    root = Path(__file__).parents[2]
    sandbox = tmp_path / "repo"
    paths = (
        "scripts/check_agents_footer_authority.py",
        "src/apm_cli/compilation/agents_compiler.py",
        "src/apm_cli/compilation/claude_formatter.py",
        "src/apm_cli/compilation/distributed_compiler.py",
        "src/apm_cli/compilation/footer.py",
        "src/apm_cli/compilation/template_builder.py",
    )
    for relative_path in paths:
        source = root / relative_path
        destination = sandbox / relative_path
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)

    consumer = sandbox / "src/apm_cli/compilation/template_builder.py"
    source = consumer.read_text(encoding="utf-8")
    source = source.replace(
        "sections.extend(build_generation_footer(agents_md_mode))",
        "sections.extend([])  # build_generation_footer( is not executable",
    )
    consumer.write_text(source, encoding="utf-8")

    result = subprocess.run(
        (sys.executable, "scripts/check_agents_footer_authority.py", str(sandbox)),
        cwd=sandbox,
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 1
    assert "template_builder.py: generated footer must use" in result.stdout
