"""Regression coverage for mode-aware generated footers (issue #2689)."""

from pathlib import Path

import pytest
from click.testing import CliRunner

from apm_cli.cli import cli
from apm_cli.compilation.distributed_compiler import (
    DistributedAgentsCompiler,
    PlacementResult,
)
from apm_cli.compilation.footer import build_generation_footer
from apm_cli.primitives.models import PrimitiveCollection

pytestmark = pytest.mark.component

_FILE_FOOTER = "*This file was generated by APM CLI. Do not edit manually.*"
_SECTION_FOOTER = "*This section was generated by APM CLI. Do not edit manually.*"
_START_MARKER = "<!-- apm:start -->"
_END_MARKER = "<!-- apm:end -->"


def test_full_mode_footer_retains_whole_file_wording() -> None:
    """The default mode must preserve the existing whole-file contract."""
    footer = build_generation_footer()

    assert _FILE_FOOTER in footer
    assert _SECTION_FOOTER not in footer


def _create_managed_project(project: Path) -> Path:
    """Create a minimal project with a managed root AGENTS.md."""
    agents_md = project / "AGENTS.md"
    agents_md.write_text(
        "# Team guidance\n\n"
        "Human-authored content.\n\n"
        f"{_START_MARKER}\n"
        "Old APM block.\n"
        f"{_END_MARKER}\n\n"
        "Human footer.\n",
        encoding="utf-8",
    )
    (project / "apm.yml").write_text(
        "name: test-project\n"
        "version: 0.1.0\n"
        "compilation:\n"
        "  source_attribution: true\n"
        "  agents_md:\n"
        "    mode: managed_section\n",
        encoding="utf-8",
    )
    instructions_dir = project / ".apm" / "instructions"
    instructions_dir.mkdir(parents=True)
    (instructions_dir / "coding.instructions.md").write_text(
        "---\n"
        "description: Test instructions\n"
        'applyTo: "**/*.py"\n'
        "---\n\n"
        "# Test instructions\n\n"
        "Use the project style.\n",
        encoding="utf-8",
    )
    return agents_md


@pytest.mark.parametrize(
    "compile_args",
    [
        pytest.param([], id="distributed"),
        pytest.param(["--single-agents"], id="single-file"),
    ],
)
def test_generated_footer_describes_managed_section(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, compile_args: list[str]
) -> None:
    """Every root AGENTS.md strategy must describe section ownership."""
    agents_md = _create_managed_project(tmp_path)
    monkeypatch.chdir(tmp_path)

    result = CliRunner().invoke(cli, ["compile", *compile_args, "--local-only"])

    assert result.exit_code == 0, result.output
    written = agents_md.read_text(encoding="utf-8")
    start = written.index(_START_MARKER)
    end = written.index(_END_MARKER)
    managed_content = written[start:end]
    assert _SECTION_FOOTER in managed_content
    assert _FILE_FOOTER not in managed_content


def test_managed_mode_keeps_subdirectory_footer_file_scoped(tmp_path: Path) -> None:
    """A fully generated nested AGENTS.md must retain file ownership wording."""
    compiler = DistributedAgentsCompiler(base_dir=str(tmp_path))
    placement = PlacementResult(
        agents_path=tmp_path / "services" / "api" / "AGENTS.md",
        instructions=[],
    )

    nested_content = compiler._generate_agents_content(
        placement, PrimitiveCollection(), agents_md_mode="managed_section"
    )

    assert _FILE_FOOTER in nested_content
    assert _SECTION_FOOTER not in nested_content
